#!/usr/bin/env python3
"""
Twitter Bookmark Clearer
Reads to_unbookmark.txt (generated by download_bookmarks.py) and helps you
remove bookmarks from Twitter/X.

Two modes:
  --mode manual   (default) Opens URLs in browser batches for manual clearing
  --mode auto     Uses Twitter GraphQL API to auto-remove bookmarks (advanced)

Safety:
  - --mode auto always does a dry-run first unless --confirm is passed
  - Logs all removals to unbookmark_log.json
  - Rate-limited between requests
"""

import argparse
import json
import os
import subprocess
import sys
import time
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path

# ============== CONFIG ==============
UNBOOKMARK_FILE = "to_unbookmark.csv"
LOG_FILE = "unbookmark_log.json"

# Batch size for manual mode (tabs opened at once)
MANUAL_BATCH_SIZE = 5

# Rate limiting for auto mode (seconds between API calls)
AUTO_MIN_DELAY = 2
AUTO_MAX_DELAY = 5

# Twitter GraphQL config (for auto mode)
TWITTER_BOOKMARK_DELETE_QUERY_ID = "BoOnR72Rt-Ag2swlQyYjyw"
TWITTER_BOOKMARK_DELETE_ENDPOINT = (
    f"https://api.x.com/graphql/{TWITTER_BOOKMARK_DELETE_QUERY_ID}/DeleteBookmark"
)
TWITTER_BEARER_TOKEN = (
    "AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D"
    "1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA"
)
# =====================================


def load_urls(filepath):
    """Load URLs from to_unbookmark.csv.
    Parses standard CSV format and extracts only the URL column.
    Falls back to plain text parsing if CSV fails.
    """
    if not os.path.exists(filepath):
        print(f"❌ File not found: {filepath}")
        print("   Run download_bookmarks.py first to generate this file")
        sys.exit(1)

    urls = []
    try:
        import csv
        with open(filepath, "r", encoding="utf-8", newline="") as f:
            reader = csv.reader(f)
            for i, row in enumerate(reader):
                if not row:
                    continue
                # Skip header row
                if i == 0 and row[0].lower() == "url":
                    continue
                # Take first column (URL)
                url = row[0].strip()
                if url and not url.startswith("#"):
                    urls.append(url)
    except Exception:
        # Fallback to plain text parsing
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    urls.append(line.split(",")[0].strip())

    if not urls:
        print(f"📄 {filepath} is empty — nothing to unbookmark")
        sys.exit(0)

    return urls


def extract_tweet_id(url):
    """Extract the numeric tweet ID from a Twitter/X URL."""
    # Handles: https://twitter.com/user/status/1234567890
    #          https://x.com/user/status/1234567890
    #          https://twitter.com/user/status/1234567890?s=20
    parts = url.split("/")
    for i, part in enumerate(parts):
        if part == "status" and i + 1 < len(parts):
            tweet_id = parts[i + 1].split("?")[0].split("#")[0]
            return tweet_id
    return None


def open_urls_in_browser(urls, batch_num, total_batches):
    """Open a batch of URLs in the default browser."""
    print(f"\n📦 Batch {batch_num}/{total_batches} — opening {len(urls)} tabs...")

    for url in urls:
        try:
            if sys.platform == "darwin":
                subprocess.Popen(["open", url])
            elif sys.platform.startswith("linux"):
                subprocess.Popen(["xdg-open", url])
            elif sys.platform == "win32":
                os.startfile(url)
            else:
                print(f"  ⚠️  Unknown OS — open manually: {url}")
                continue
            print(f"  ✅ Opened: {url}")
        except Exception as e:
            print(f"  ❌ Failed to open: {url} ({e})")

    print(f"\n⏸️  Review the {len(urls)} tabs in your browser.")
    print(f"   Click the bookmark icon on each tweet to remove it.")
    input(f"   Press ENTER when done with this batch...")


def manual_mode(urls, batch_size=MANUAL_BATCH_SIZE):
    """Open URLs in browser batches for manual unbookmarking."""
    total_batches = (len(urls) + batch_size - 1) // batch_size

    print(f"📋 Manual unbookmark mode")
    print(f"   {len(urls)} URLs to process")
    print(f"   Batch size: {MANUAL_BATCH_SIZE} tabs at a time")
    print(f"   Total batches: {total_batches}")
    print(f"\n   For each tweet: click the bookmark icon to remove it from your bookmarks.")
    print(f"   Close the tab when done.\n")
    input("   Press ENTER to start opening tabs...")

    for i in range(0, len(urls), MANUAL_BATCH_SIZE):
        batch = urls[i : i + MANUAL_BATCH_SIZE]
        batch_num = (i // MANUAL_BATCH_SIZE) + 1
        open_urls_in_browser(batch, batch_num, total_batches)

    print(f"\n✅ All batches processed!")
    print(f"   You've reviewed {len(urls)} tweets.")
    print(f"   Remember: this script can't verify bookmarks were actually removed.")
    print(f"   Check your Twitter bookmarks page to confirm.")


def load_cookies_for_api():
    """Load auth_token and ct0 from cookies.txt for API calls."""
    if not os.path.exists("cookies.txt"):
        print("❌ cookies.txt required for auto mode")
        print("   This file must contain your Twitter auth_token and ct0 cookies")
        sys.exit(1)

    auth_token = None
    ct0 = None

    with open("cookies.txt", "r") as f:
        for line in f:
            line = line.strip()
            if line.startswith("#") or not line:
                continue
            parts = line.split("\t")
            if len(parts) >= 7:
                name = parts[5]
                value = parts[6]
                if name == "auth_token":
                    auth_token = value
                elif name == "ct0":
                    ct0 = value

    if not auth_token or not ct0:
        print("❌ Could not find auth_token and ct0 in cookies.txt")
        print("   Make sure your cookies file includes these Twitter session cookies")
        sys.exit(1)

    return auth_token, ct0


def api_delete_bookmark(tweet_id, auth_token, ct0):
    """Send a DeleteBookmark GraphQL request to Twitter."""
    body = json.dumps({"variables": {"tweet_id": tweet_id}, "queryId": TWITTER_BOOKMARK_DELETE_QUERY_ID}).encode()

    headers = {
        "Authorization": f"Bearer {TWITTER_BEARER_TOKEN}",
        "Cookie": f"auth_token={auth_token}; ct0={ct0}",
        "x-csrf-token": ct0,
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "Referer": "https://x.com/",
        "Origin": "https://x.com",
    }

    req = urllib.request.Request(
        TWITTER_BOOKMARK_DELETE_ENDPOINT,
        data=body,
        headers=headers,
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=15) as response:
            result = json.loads(response.read().decode())
            return True, result
    except urllib.error.HTTPError as e:
        error_body = e.read().decode()[:200] if e.fp else ""
        return False, f"HTTP {e.code}: {error_body}"
    except Exception as e:
        return False, str(e)


def auto_mode(urls, confirm=False):
    """Automatically remove bookmarks via Twitter GraphQL API."""
    auth_token, ct0 = load_cookies_for_api()

    print(f"\n🤖 Auto unbookmark mode")
    print(f"   {len(urls)} bookmarks to remove")

    # Parse tweet IDs
    tweet_data = []
    for url in urls:
        tweet_id = extract_tweet_id(url)
        if tweet_id:
            tweet_data.append({"url": url, "tweet_id": tweet_id})
        else:
            print(f"  ⚠️  Could not extract tweet ID from: {url}")

    if not tweet_data:
        print("\n❌ No valid tweet IDs found")
        sys.exit(1)

    print(f"   Parsed {len(tweet_data)} tweet IDs\n")

    # Dry run
    if not confirm:
        print(f"━" * 60)
        print(f"🔍 DRY RUN — no bookmarks will be removed")
        print(f"━" * 60) 
        print(f"\nThe following {len(tweet_data)} bookmarks would be removed:")
        for i, item in enumerate(tweet_data, 1):
            print(f"  {i:>4}. Tweet ID: {item['tweet_id']}")
            print(f"       URL: {item['url']}")

        print(f"\n{'=' * 60}")
        print(f"To actually remove these bookmarks, run:")
        print(f"  python {os.path.basename(__file__)} --mode auto --confirm")
        print(f"{'=' * 60}")
        return

    # Confirmed — proceed with deletion
    print(f"⚠️  CONFIRMED — proceeding with bookmark deletion")
    print(f"   Press Ctrl+C within 5 seconds to cancel...")
    time.sleep(5)

    log = {
        "timestamp": datetime.now().isoformat(),
        "mode": "auto",
        "total": len(tweet_data),
        "removed": [],
        "failed": [],
    }

    for i, item in enumerate(tweet_data, 1):
        print(f"\n[{i}/{len(tweet_data)}] Removing bookmark for tweet {item['tweet_id']}...")

        success, result = api_delete_bookmark(item["tweet_id"], auth_token, ct0)

        if success:
            print(f"  ✅ Removed")
            log["removed"].append({
                "url": item["url"],
                "tweet_id": item["tweet_id"],
                "timestamp": datetime.now().isoformat(),
            })
        else:
            print(f"  ❌ Failed: {result}")
            log["failed"].append({
                "url": item["url"],
                "tweet_id": item["tweet_id"],
                "error": str(result),
                "timestamp": datetime.now().isoformat(),
            })

        # Rate limiting
        if i < len(tweet_data):
            import random
            delay = random.uniform(AUTO_MIN_DELAY, AUTO_MAX_DELAY)
            time.sleep(delay)

    # Save log
    with open(LOG_FILE, "w", encoding="utf-8") as f:
        json.dump(log, f, indent=2, ensure_ascii=False)

    # Summary
    print(f"\n{'=' * 60}")
    print(f"📊 COMPLETE")
    print(f"{'=' * 60}")
    print(f"✅ Removed:  {len(log['removed'])}")
    print(f"❌ Failed:   {len(log['failed'])}")
    print(f"📄 Log saved: {LOG_FILE}")

    if log["failed"]:
        print(f"\n⚠️  {len(log['failed'])} bookmarks could not be removed.")
        print(f"   Check {LOG_FILE} for details. These may already be un-bookmarked.")


def main():
    parser = argparse.ArgumentParser(
        description="Clear Twitter bookmarks from a URL list",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python clear_bookmarks.py                    # Manual mode (opens browser tabs)
  python clear_bookmarks.py --mode auto        # Auto mode dry-run
  python clear_bookmarks.py --mode auto --confirm  # Auto mode actual deletion
  python clear_bookmarks.py --batch-size 10    # Manual mode, 10 tabs per batch
        """,
    )
    parser.add_argument(
        "--mode",
        choices=["manual", "auto"],
        default="manual",
        help="Unbookmark mode (default: manual)",
    )
    parser.add_argument(
        "--confirm",
        action="store_true",
        help="Confirm auto mode deletion (skips dry-run)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=MANUAL_BATCH_SIZE,
        help=f"Number of tabs per batch in manual mode (default: {MANUAL_BATCH_SIZE})",
    )
    parser.add_argument(
        "--file",
        default=UNBOOKMARK_FILE,
        help=f"URL list file (default: {UNBOOKMARK_FILE})",
    )

    args = parser.parse_args()

    # Load URLs
    urls = load_urls(args.file)
    print(f"📋 Loaded {len(urls)} URLs from {args.file}")

    if args.mode == "manual":
        manual_mode(urls, batch_size=args.batch_size)
    elif args.mode == "auto":
        auto_mode(urls, confirm=args.confirm)


if __name__ == "__main__":
    main()
